name: cadastro
description: "Cadastro de livros"
publish_to: 'none'
version: 0.1.6

environment:
  sdk: '>=3.2.0-38.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  mysql1: ^0.19.0
  path_provider: ^2.1.0
  path: ^1.8.3
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/sample.db
